[phases.setup]
nixPkgs = ["ffmpeg", "python3", "curl"]

[phases.build]
cmds = [
  "mkdir -p bin",
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o bin/yt-dlp",
  "chmod +x bin/yt-dlp",
  "npm run build"
]

[start]
cmd = "node dist/index.js"